//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;
    
    public partial class Book
    {
        public int Bid { get; set; }
        [Required(ErrorMessage ="Give a title")]
        public string Book_title { get; set; }
        [Required(ErrorMessage = "Give arthor name")]
        public string Book_arthor { get; set; }
        [DisplayName("Upload Picture")]
        public byte[] Book_image { get; set; }
        [Required(ErrorMessage = "Give isbn")]
        public string Book_isbn { get; set; }
        public string available { get; set; }
    }
}
