//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookIssue2
    {
        public int lid { get; set; }
        public string Senrollment { get; set; }
        public string Book_isbn { get; set; }
        public string issue_date { get; set; }
        public string Return_date { get; set; }
        public string Susername { get; set; }
        public string is_book_return { get; set; }
    }
}
