//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Borrow_List
    {
        public int b_id { get; set; }
        public int s_id { get; set; }
        public System.DateTime issue_date { get; set; }
        public System.DateTime return_time { get; set; }
    }
}
